/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Commit information returned to JavaScript */
export interface JjCommitInfo {
  id: string
  changeId: string
  description: string
  authorName: string
  authorEmail: string
  authorTimestamp: number
  committerName: string
  committerEmail: string
  committerTimestamp: number
  parentIds: Array<string>
  isEmpty: boolean
}
/** File change information */
export interface JjFileChange {
  path: string
  changeType: string
}
/** Branch information */
export interface JjBranchInfo {
  name: string
  targetId?: string
  isLocal: boolean
  remote?: string
}
/** Operation information */
export interface JjOperationInfo {
  id: string
  description: string
  timestamp: number
}
/** Check if a path contains a jj workspace */
export declare function isJjWorkspace(path: string): boolean
/** Check if a path contains a git repository */
export declare function isGitRepo(path: string): boolean
/** Main JJ Workspace wrapper */
export declare class JjWorkspace {
  /** Initialize a new jj workspace at the given path */
  static init(path: string): JjWorkspace
  /** Initialize a jj workspace from an existing git repository */
  static initColocated(path: string): JjWorkspace
  /** Open an existing jj workspace */
  static open(path: string): JjWorkspace
  /** Get the workspace root path */
  get root(): string
  /** Get the repository path */
  get repoPath(): string
  /** Get commit by ID (hex string) */
  getCommit(commitId: string): JjCommitInfo
  /**
   * List all bookmarks (formerly branches)
   * Also includes git branches for colocated repos where git refs haven't been imported
   */
  listBookmarks(): Array<JjBranchInfo>
  /** Get the current operation info */
  getCurrentOperation(): JjOperationInfo
  /** Get the root commit (empty initial commit) */
  getRootCommit(): JjCommitInfo
  /** List all heads (commits with no children) */
  listHeads(): Array<string>
  /** List all files at a specific revision (change_id, commit_id, or bookmark name) */
  listFiles(revision: string): Array<string>
  /** Get file content at a specific revision */
  getFileContent(revision: string, path: string): string | null
  /** List recent changes/commits with full info */
  listChanges(limit?: number | undefined | null, bookmark?: string | undefined | null): Array<JjCommitInfo>
}
