/* auto-generated by NAPI-RS - manually adjusted for documentation */

export interface JjCommitInfo {
  /** Full hex commit ID */
  id: string;
  /** Change ID (jj's unique identifier) */
  changeId: string;
  /** Commit description/message */
  description: string;
  /** Author name */
  authorName: string;
  /** Author email */
  authorEmail: string;
  /** Author timestamp (Unix epoch seconds) */
  authorTimestamp: number;
  /** Committer name */
  committerName: string;
  /** Committer email */
  committerEmail: string;
  /** Committer timestamp (Unix epoch seconds) */
  committerTimestamp: number;
  /** Parent commit IDs */
  parentIds: string[];
  /** Whether the commit is empty (no changes) */
  isEmpty: boolean;
}

export interface JjFileChange {
  /** File path */
  path: string;
  /** Change type: "added", "modified", or "deleted" */
  changeType: string;
}

export interface JjBranchInfo {
  /** Branch name */
  name: string;
  /** Target commit ID (null if conflicted) */
  targetId: string | null;
  /** Whether this is a local branch */
  isLocal: boolean;
  /** Remote name (null for local branches) */
  remote: string | null;
}

export interface JjOperationInfo {
  /** Operation ID */
  id: string;
  /** Operation description */
  description: string;
  /** Timestamp (Unix epoch seconds) */
  timestamp: number;
}

/**
 * Main JJ Workspace wrapper - provides access to jj repository operations
 */
export class JjWorkspace {
  /** Workspace root path */
  readonly root: string;
  /** Repository path (usually .jj directory) */
  readonly repoPath: string;

  /**
   * Initialize a new jj workspace with internal git backend
   * @param path - Path to initialize the workspace
   */
  static init(path: string): JjWorkspace;

  /**
   * Initialize a jj workspace colocated with an existing git repository
   * @param path - Path to the existing git repository
   */
  static initColocated(path: string): JjWorkspace;

  /**
   * Open an existing jj workspace
   * @param path - Path to the workspace root
   */
  static open(path: string): JjWorkspace;

  /**
   * Get the current working copy commit
   */
  getWorkingCopyCommit(): JjCommitInfo;

  /**
   * Query commits using jj's revset language
   * @param revsetStr - Revset expression (e.g., "ancestors(@, 10)", "branches()")
   * @see https://martinvonz.github.io/jj/latest/revsets/
   */
  query(revsetStr: string): JjCommitInfo[];

  /**
   * Get a specific commit by its ID
   * @param commitId - Full or prefix hex commit ID
   */
  getCommit(commitId: string): JjCommitInfo;

  /**
   * List all branches (local and remote)
   */
  listBranches(): JjBranchInfo[];

  /**
   * List operation history
   * @param limit - Maximum number of operations to return (default: 50)
   */
  listOperations(limit?: number): JjOperationInfo[];

  /**
   * Get file changes in the working copy compared to its parent
   */
  status(): JjFileChange[];
}

/**
 * Check if a path contains a jj workspace (.jj directory)
 */
export function isJjWorkspace(path: string): boolean;

/**
 * Check if a path contains a git repository (.git directory)
 */
export function isGitRepo(path: string): boolean;
